apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agrotech-infra-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/eurival/agrotech-ops.git # <--- SEU GIT
    targetRevision: HEAD
    path: infra # Aponta para a pasta onde estão os componentes
    directory:
      recurse: true # Pega subpastas (kafka, postgis, monitoring)
  destination:
    server: https://kubernetes.default.svc
    namespace: agrotech
  syncPolicy:
    automated:
      prune: true    # Se deletar no Git, deleta no K8s
      selfHeal: true # Se mudar no K8s na mão, o Argo reverte
    syncOptions:
      - CreateNamespace=true