apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: agrotech-project
  namespace: argocd
spec:
  description: Projeto IoT e Big Data para Agricultura
  sourceRepos:
  - "https://github.com/eurival/agrotech-ops.git" # (Ajuste para seu user real)

  destinations:
  # Onde vão ficar os apps de negócio (Kafka, Spark, etc)
  - namespace: agrotech
    server: https://kubernetes.default.svc
  # Onde fica o Spark Operator
  - namespace: spark-operator-system
    server: https://kubernetes.default.svc
  # CORREÇÃO CRÍTICA: Permite que o Argo crie as definições "App of Apps" dentro dele mesmo
  - namespace: argocd
    server: https://kubernetes.default.svc

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'